### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by gonzaliski** [PabloMartinsDeMaltoz/Desafio-M5#1]
Hola Pablo! Antes que nada felicitarte por el desafío. Lo único que te puedo llegar a recomendar, que es una pavada, es tener cuidado con los nombres de las pages. En esta altura que estamos no es muy relevante esto ya que se entiende con leerlo un poco, pero en el futuro estaría bueno utilizar nombres mas descriptivos (Ej: /game, /result, /welcome, etc.). Así que yo apruebo el desafío! Nuevamente felicitaciones y a seguir adelante! :)

**Comment by PabloMartinsDeMaltoz** [comment]
Gracias por la devolución , si es verdad creo que dije lo cambio antes de subirlo y se me paso xD. Saludos
